---
title: Greg Baker
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
exclude: ["Gemfile.lock", "node_modules"]
email: 
description: Greg Baker's home on the web, powered by Jekyll and GitHub Pages.
twitter_username: gblegalco
github_username: gblegal
minimal_mistakes_skin: default
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
author:
  name: Greg Baker
  avatar: "/assets/images/bio-photo.jpg"
  bio: Solicitor, legal technologist, father & husband.
  links:
  - label: Home
    icon: fas fa-fw fa-link
    url: https://greg-baker.com
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/gblegalco
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/gblegal/
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/gblegal/
footer:
  links:
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/gblegalco
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/gblegal
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/gblegal/
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
