# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Greg Baker
title: Lead Innovation Lawyer
email: greg.baker@linklaters.com
website: www.linkedin.com/in/gblegal

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: gblegalco
github_username:  gblegal
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: gblegal
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Greg Baker
  icon: fas fa-globe
  url: https://greg-baker.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Greg. I'm a lawyer and legal technologist in the M&A practice at a leading international law firm based in London.
  
  My role includes:
  
    - driving adoption of innovative working methods
    - looking for opportunities to exploit data for both know-how and transaction-related purposes
    - enabling our amazing lawyers to fully utilise technical innovations and efficiency tools
    - acting as a matter consultant to enable our lawyers to deliver outstanding and efficient client service 

  I am most skilled in: understanding the <mark>business of law</mark>, improving <mark>the way lawyers work</mark>, plus both at work & at home <mark>playing with and assessing the latest tech innovations!</mark>.

content:
  - title: Other Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: GitHub Pages, Jekyll
        link: github.com/gblegal
        # link_text: Project Website
        additional_links:
          - title:  Re-learning web design and HTML
            icon: fab fa-github
            url: github.com/gblegal
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I used to know all of this stuff, but other things crowded it out.
        description: | # this will include new lines to allow paragraphs
          I am using this website and a few others to refamiliarise myself with some basic web technologies, hosting strategies and general web publishing.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: White & Case
        link: whitecase.com
        # link_text: boringcompany.com
        sub_title: Trainee, Associate
        caption: September 2008 - June 2018
        quote: >
          Trained, qualified and practiced across a range of different practice areas, together with a number of secondments.
        description: | # this will include new lines to allow paragraphs
            More details upon request.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: College of Law
        caption: 2005 - 2006; 2007 - 2008
        sub_title: GDL & LPC
        quote: >
          GDL, followed by a year at BNP Paribas' TMT Lev Fin team, before returning for the LPC.
        description: | # this will include new lines to allow paragraphs
          More details upon request.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in the law, innovation and legal technology some of my other interests and hobbies are:
      - Photography
      - Wine
      - Rowing
      - Home automation

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
